version: '3'
services:
    db:
        image: mysql:5.7
        container_name: mysql-db
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        restart: always
        environment:
          MYSQL_ROOT_PASSWORD: "passwordroot"
          MYSQL_USER: test
          MYSQL_PASSWORD: "passwordtest"
        ports:
          - '6606:3306'
        volumes:
          - /home/mysql/data:/var/lib/mysql
          - /home/mysql/conf/my.cnf:/etc/mysql/my.cnf